/* auto-generated by NAPI-RS */
/* eslint-disable */
/** 在分组下新增一个分组 */
export declare function addMenuGroup(newGroup: MenuGroup, modifyInfo: ModifyInfo, filePathConfig: FilePathConfig): CodeGenerateResult

export interface CodeGenerateResult {
  files: Array<FileInfo>
}

export declare function createMyBatisXml(): string

export interface FileInfo {
  path: string
  operation: FileOperation
  message: string
}

export declare const enum FileOperation {
  Add = 0,
  Modify = 1,
  Delete = 2,
  Ignore = 3
}

export interface FilePathConfig {
  liquibaseRootFileFullPath: string
  liquibaseRootFileIncludePath: string
  liquibaseMenuGroupInsertFilePath: string
}

export interface MenuGroup {
  id: number
  key: string
  title: string
  icon: string
  route: string
  seq: number
  /** 默认为 0 */
  parentId: number
  /** 客户端类型 */
  clientType?: string
}

export interface ModifyInfo {
  author: string
  time: string
}

export declare function plus100(input: number): number

export declare function sum(a: number, b: number): number
