/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class PageInfo {
  parentKeys: Array<string>
  pageKey: string
  pageName: string
}

/** 在分组下新增一个分组 */
export declare function addMenuGroup(newGroup: MenuGroup, changeSetInfo: ChangeSetInfo, filePathConfig: FilePathConfig): CodeGenerateResult

/** 在分组下新增一个菜单 */
export declare function addMenuItem(newMenuItem: MenuItem, changeSetInfo: ChangeSetInfo, filePathConfig: FilePathConfig): CodeGenerateResult

/**
 * 新增一个 typescript d.ts 文件
 * ## Parameters
 * * `types_root_dir`: types 文件的根目录，绝对路径，如 ``
 * * `name`: The identifier name being bound.
 */
export declare function addTsTypes(typesRootDir: string, pathParts: Array<string>, mainTable: DbTableStructure, subTables: Array<DbTableStructure>, pageName: string | undefined | null, queryColumns: Array<DbColumn>): CodeGenerateResult

export interface ChangeSetInfo {
  author: string
  id: string
}

export interface CodeGenerateResult {
  files: Array<FileInfo>
}

export declare function createMyBatisXml(): string

/** 列信息 */
export interface DbColumn {
  name: string
  comment: string
  /** 数据类型 */
  dataType: DbDataType
  maxLength?: number
  scale?: number
  /** 只有当数字类型时，此字段才需要赋值；否则值为 None */
  unsigned?: boolean
  /** 是否为主键列，所有列要么是，要么不是 */
  primary: boolean
  /** 是否可控，所有列要么可空，要么不可空 */
  nullable: boolean
  defaultValue?: string
  dbUnitName?: string
  uiUnitName?: string
  afterColumnName?: string
  /** 当列与表分开传入时，通过 table_name 与表结构定义建立关系；否则值为 None */
  tableName?: string
}

export declare const enum DbDataType {
  Boolean = 'boolean',
  Char = 'char',
  Varchar = 'varchar',
  NChar = 'nchar',
  NVarchar = 'nvarchar',
  Clob = 'clob',
  Number = 'number',
  TinyInt = 'tinyint',
  SmallInt = 'smallint',
  MediumInt = 'mediumint',
  Int = 'int',
  BigInt = 'bigint',
  Float = 'float',
  Double = 'double',
  Decimal = 'decimal',
  Currency = 'currency',
  Date = 'date',
  DateTime = 'datetime',
  Time = 'time',
  Timestamp = 'timestamp',
  Uuid = 'uuid',
  Blob = 'blob',
  Xml = 'xml',
  Json = 'json',
  TinyText = 'tinytext',
  MediumText = 'mediumtext',
  LongText = 'longtext',
  TinyBlob = 'tinyblob',
  MediumBlob = 'mediumblob',
  LongBlob = 'longblob'
}

/** 数据库表基本信息 */
export interface DbTable {
  /** 表名 */
  name: string
  /** 注释 */
  comment: string
}

/**
 * 定义一张数据库表结构。
 * 包括表基本信息，字段列表，唯一约束列表，外键约束列表
 */
export interface DbTableStructure {
  table: DbTable
  columns: Array<DbColumn>
  uniqueConstraints: Array<UniqueConstraint>
  foreignConstraints: Array<ForeignConstraint>
}

export interface FileInfo {
  path: string
  operation: FileOperation
  message: string
}

export declare const enum FileOperation {
  Add = 0,
  Modify = 1,
  Delete = 2,
  Ignore = 3
}

export interface FilePathConfig {
  /** liquibase changelog 根文件的完整路径 */
  liquibaseRootFileFullPath: string
  /** liquibase 新增文件的完整路径 */
  liquibaseNewFileFullPath: string
  /** liquibase 新增文件往根文件中引入的相对路径 */
  liquibaseNewFileIncludePath: string
}

/** 外键约束 */
export interface ForeignConstraint {
  name: string
  baseTable: DbTable
  baseColumn: DbColumn
  refTable: DbTable
  refColumn: DbColumn
}

export interface Form {
  /** form 表单的名称 */
  name: string
  /** 字段列表 */
  fields: Array<FormField>
}

export interface FormDatePicker {
  property: string
  label: string
  required: boolean
}

export type FormField =
  | { type: 'TextInput', field0: FormTextInput }
  | { type: 'NumberInput', field0: FormNumberInput }
  | { type: 'Textarea', field0: FormTextarea }
  | { type: 'DatePicker', field0: FormDatePicker }
  | { type: 'Select', field0: FormSelect }

export interface FormNumberInput {
  property: string
  label: string
  required: boolean
}

export interface FormSelect {
  property: string
  label: string
  required: boolean
}

export interface FormTextarea {
  property: string
  label: string
  required: boolean
}

export interface FormTextInput {
  property: string
  label: string
  required: boolean
}

export declare function generateVueScript(uiPage: UiPage): string

/** 判断当前目录是不是多模块的 maven 项目 */
export declare function isMavenMultipleModuleProject(projectRootPath: string): boolean

export declare const enum MatchOperation {
  Contains = 'Contains',
  Equal = 'Equal',
  Between = 'Between',
  ItemEqual = 'ItemEqual',
  ItemContains = 'ItemContains'
}

export interface MenuGroup {
  id: number
  key: string
  title: string
  icon: string
  route: string
  seq: number
  /** 默认为 0 */
  parentId: number
  /** 客户端类型 */
  clientType?: string
}

export interface MenuItem {
  id: number
  key: string
  title: string
  icon: string
  route: string
  seq: number
  /** 默认为 0 */
  parentId: number
  /** 客户端类型 */
  clientType?: string
  /** 组件地址 */
  component?: string
  /** 权限字符串 */
  perms?: string
  /** 是否为外链 */
  isFrame: boolean
  /** 是否缓存 */
  isCache: boolean
  /** 显示状态 */
  visible: boolean
}

export declare function newMavenModule(projectRootDir: string, moduleName: string, basePackage: string, moduleDescription?: string | undefined | null): string

/** 通用数值/字符串联合类型，对应 TS 的 `number | string` */
export type NumberOrString =
  | { type: 'Number', field0: number }
  | { type: 'String', field0: string }

export declare function plus100(input: number): number

/** 查询条件 */
export interface QueryParam {
  tableName: string
  columnName: string
  dataType: DbDataType
  operation: MatchOperation
}

export declare function sum(a: number, b: number): number

export declare function supportLiquibase(projectRootDir: string, moduleName: string, basePackage: string, author: string): string

export interface TableParamActionSlot {
  actions: Array<UIParamActionKey>
}

export interface TableParamItem {
  /** 属性名，对应实体类的字段名 */
  property: string
  /** 底层用一套最全面详尽的类型系统，不一层一层推导，而是基于这一套类型系统推导出不同语言的类型系统？ */
  dbDataType: DbDataType
  /** 比较操作 */
  operation: MatchOperation
}

/** 表格一级的参数容器对象 */
export interface TableParamSlot {
  /** 参数对象的名称 */
  name: string
  /** 参数列表 */
  children: Array<TableParamItem | TableParamActionSlot>
}

export declare const enum UIComponentKey {
  TextInput = 'TextInput',
  NumberInput = 'NumberInput',
  Textarea = 'Textarea',
  DatePicker = 'DatePicker',
  Select = 'Select',
  DictSelect = 'DictSelect',
  DictCheckbox = 'DictCheckbox',
  DictRadio = 'DictRadio',
  ImageUpload = 'ImageUpload',
  FileUpload = 'FileUpload',
  Editor = 'Editor'
}

export interface UiPage {
  parentPaths: Array<string>
  content: string
}

export declare const enum UIParagraphType {
  None = 'None',
  Data = 'Data',
  Ui = 'Ui',
  Changelog = 'Changelog'
}

export declare const enum UIParamActionKey {
  ListQuery = 'list_query',
  FormReset = 'form_reset'
}

/** 唯一约束 */
export interface UniqueConstraint {
  name: string
  columns: Array<DbColumn>
}
