/* auto-generated by NAPI-RS */
/* eslint-disable */
/** 在分组下新增一个分组 */
export declare function addMenuGroup(newGroup: MenuGroup, changeSetInfo: ChangeSetInfo, filePathConfig: FilePathConfig): CodeGenerateResult

export interface ChangeSetInfo {
  author: string
  id: string
}

export interface CodeGenerateResult {
  files: Array<FileInfo>
}

export declare function createMyBatisXml(): string

export interface FileInfo {
  path: string
  operation: FileOperation
  message: string
}

export declare const enum FileOperation {
  Add = 0,
  Modify = 1,
  Delete = 2,
  Ignore = 3
}

export interface FilePathConfig {
  /** liquibase changelog 根文件的完整路径 */
  liquibaseRootFileFullPath: string
  /** liquibase 新增文件的完整路径 */
  liquibaseNewFileFullPath: string
  /** liquibase 新增文件往根文件中引入的相对路径 */
  liquibaseNewFileIncludePath: string
}

export interface MenuGroup {
  id: number
  key: string
  title: string
  icon: string
  route: string
  seq: number
  /** 默认为 0 */
  parentId: number
  /** 客户端类型 */
  clientType?: string
}

export declare function plus100(input: number): number

export declare function sum(a: number, b: number): number
